<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_18888.00</name>
   <tag></tag>
   <elementGuidId>f133fb29-e2f4-4c40-994d-013b35cfadb0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*/text()[normalize-space(.)='$']/parent::*</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.ms-Link.CabinGrades-module--price-link--k-YH9.root-202</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>12aeeb6b-65b6-4a7b-b009-de4c5cd10b5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/cabin/?cabinGradeCode=S3&amp;rateCode=THN&amp;cruiseId=G322N&amp;totalGrossPrice=1888800</value>
      <webElementGuid>03818ff6-86b2-42f7-81d9-3ca175fdae8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ms-Link CabinGrades-module--price-link--k-YH9 root-202</value>
      <webElementGuid>1f724aaf-3cc2-457c-9a4a-6c53040721de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>385ce614-3f9f-4658-9664-cc2f0632fe83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>$18888.00</value>
      <webElementGuid>525bfbed-6d28-4284-9bb3-c4fbe9401d25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;row913-0&quot;)/div[@class=&quot;ms-DetailsRow-fields fields-199&quot;]/div[@class=&quot;ms-DetailsRow-cell cell-205 cellUnpadded-193&quot;]/div[@class=&quot;CabinGrades-module--dataCell--AXN3E&quot;]/a[@class=&quot;ms-Link CabinGrades-module--price-link--k-YH9 root-202&quot;]</value>
      <webElementGuid>6dc3bc31-c57c-4dfa-bb94-f8d97a619df7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='row913-0']/div/div[2]/div/a</value>
      <webElementGuid>569c42bc-d2ce-4b61-8c3b-8b2219967319</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('', '&quot;', 'no deck data', '&quot;', '')])[1]/following::a[1]</value>
      <webElementGuid>18f2ae7d-830a-45c6-ba1c-ed2a5b4f3bb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='S3'])[1]/following::a[1]</value>
      <webElementGuid>2d874083-3d15-442d-965f-c77d97b98db4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$14488.00'])[1]/preceding::a[1]</value>
      <webElementGuid>f210d1c7-2543-42db-b41c-4f036871642e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$15688.00'])[1]/preceding::a[2]</value>
      <webElementGuid>e0b50fd5-6098-406a-bd95-50938ad49072</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='$']/parent::*</value>
      <webElementGuid>ff891ec3-b33b-4bea-b7b9-5430ac4d1e8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/cabin/?cabinGradeCode=S3&amp;rateCode=THN&amp;cruiseId=G322N&amp;totalGrossPrice=1888800')]</value>
      <webElementGuid>83bce84e-2585-4a10-bc3c-29a6be44a87e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/a</value>
      <webElementGuid>99ad3d8f-a476-488a-aba3-ed195bf78cd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/cabin/?cabinGradeCode=S3&amp;rateCode=THN&amp;cruiseId=G322N&amp;totalGrossPrice=1888800' and (text() = '$18888.00' or . = '$18888.00')]</value>
      <webElementGuid>c024f6de-6ec2-43a5-af72-acf99c28e370</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
