<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_searchsearch</name>
   <tag></tag>
   <elementGuidId>208a9d3f-5e9a-4583-a4fb-a1d793fc8740</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Traveltek Cruise Search'])[1]/following::a[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.ms-Link.ms-Breadcrumb-itemLink.itemLink-107</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a69d8c70-3510-4eca-b98d-0d5133ae504e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/</value>
      <webElementGuid>4e5ab889-2778-46c0-8757-6a855634514f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ms-Link ms-Breadcrumb-itemLink itemLink-107</value>
      <webElementGuid>c106552d-d1d0-43a5-93c8-4c309c38b129</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>1c7ca6be-f605-4143-92e0-4012eee67169</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>searchsearch</value>
      <webElementGuid>1fa8bc7a-320d-4a1e-8dab-7363b3407c15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gatsby-focus-wrapper&quot;)/div[@class=&quot;GenericLayout-module--container--9rlo1&quot;]/main[1]/div[1]/div[1]/div[1]/div[1]/div[@class=&quot;ms-Breadcrumb root-98&quot;]/div[@class=&quot;ms-FocusZone css-106&quot;]/ol[@class=&quot;ms-Breadcrumb-list list-99&quot;]/li[@class=&quot;ms-Breadcrumb-listItem listItem-100&quot;]/a[@class=&quot;ms-Link ms-Breadcrumb-itemLink itemLink-107&quot;]</value>
      <webElementGuid>f465329a-4eef-4309-adf9-21071f996898</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gatsby-focus-wrapper']/div/main/div/div/div/div/div/div/ol/li/a</value>
      <webElementGuid>15844efe-ffe9-4978-8050-57aa548d48f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Traveltek Cruise Search'])[1]/following::a[1]</value>
      <webElementGuid>19463b93-5921-46b7-a7f5-7c647f51f193</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/')]</value>
      <webElementGuid>e1813ac7-e80d-4171-a71e-3dec526b4947</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>7170ae5a-9e8c-4b58-851e-aa2c53355288</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/' and (text() = 'searchsearch' or . = 'searchsearch')]</value>
      <webElementGuid>d9182edf-4fb1-4d8a-9ea5-208f54c8c578</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
