<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_</name>
   <tag></tag>
   <elementGuidId>cd97f6ad-0687-4ea0-a84b-75a7595e12cf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#row47-0-checkbox</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='row47-0-checkbox']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>54cc0c7f-d4c4-4f96-bf12-6f59cb54714b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>row47-0-checkbox</value>
      <webElementGuid>c0933243-7580-4d48-aea2-258b7af97899</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>select a cabin</value>
      <webElementGuid>59d5e597-0f17-435c-b7f2-0f4094fe03ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>row47-0-checkbox</value>
      <webElementGuid>2b7f6833-de72-474c-bb09-0d1e757d3800</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>381ff7bf-bf95-465d-b45b-5d7a73fc44be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ms-DetailsRow-check ms-Check-checkHost check-166</value>
      <webElementGuid>1427fc12-76bb-495f-923a-1af24cb0e134</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-checked</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9ef1f220-c374-4e48-8082-9f980fcf5cd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-selection-toggle</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6da96621-4578-4d5d-ada7-d55c763b6da7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automationid</name>
      <type>Main</type>
      <value>DetailsRowCheck</value>
      <webElementGuid>f3270aee-5f3f-40a8-8dac-ccc7d37c9d52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>5c69eba7-5205-48c8-890b-e5967e4c44af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>ee526648-649f-41ae-9a7c-24b034f676c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;row47-0-checkbox&quot;)</value>
      <webElementGuid>e9a4fd58-9b26-44c6-b7a7-99fe272cfd62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7956358e-135e-4756-84d3-09ac37123806</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ms-Checkbox-checkbox checkbox-164</value>
      <webElementGuid>670e2eb4-f4da-46f5-9869-5bf2e5dabbad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ktp-target</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4be68f3a-80df-4c16-a63d-ef1ff7fad506</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>23b8e592-8470-4e44-8b52-ed3dc7e11acf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cruise-line-filter-content&quot;)/div[@class=&quot;AccordionItem-module--item-spacing--Up8JF&quot;]/div[@class=&quot;ms-Stack css-160&quot;]/div[@class=&quot;ms-Checkbox is-enabled root-161&quot;]/label[@class=&quot;ms-Checkbox-label label-163&quot;]/div[@class=&quot;ms-Checkbox-checkbox checkbox-164&quot;]</value>
      <webElementGuid>904826d9-104b-423e-83d7-8dbd347ce372</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='row47-0-checkbox']</value>
      <webElementGuid>a81f6bdb-77cb-4222-aadb-7fd243c32b48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='row47-0']/div/div</value>
      <webElementGuid>d8675599-db95-426f-a98e-3d4d9767a5f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Accessibility'])[1]/following::div[10]</value>
      <webElementGuid>61232ba9-d3d5-4271-b48e-1221a0ae73ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Obstruction'])[1]/following::div[11]</value>
      <webElementGuid>b96aae7d-303f-4c35-91c9-576d04873b52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='D726'])[1]/preceding::div[3]</value>
      <webElementGuid>555a4893-21f1-48d2-85d8-04e68ea32bba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dolphin'])[1]/preceding::div[5]</value>
      <webElementGuid>0ebcc206-62ec-42c5-8bc4-733ee61e4532</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/div/div/div</value>
      <webElementGuid>cf200196-24e8-442f-a863-3d871b590450</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'row47-0-checkbox' and (text() = '' or . = '')]</value>
      <webElementGuid>a8d567ec-c084-48d6-ba91-4c846492315b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cruise-line-filter-content']/div/div/div[2]/label/div</value>
      <webElementGuid>fbea4b34-d818-4a9f-a6ea-f402eb3b61cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cunard (110)'])[1]/following::div[2]</value>
      <webElementGuid>fdf5dff2-b6eb-44c6-9a54-58239d52344e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cruise Line'])[1]/following::div[7]</value>
      <webElementGuid>e608d7c6-b928-4d67-988a-ac83a1742033</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Princess (235)'])[1]/preceding::div[1]</value>
      <webElementGuid>ba7955dc-5056-4d50-9722-fe466adc96af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Seabourn (5)'])[1]/preceding::div[2]</value>
      <webElementGuid>27664738-21fa-4d31-ba49-559a36c9aa62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/label/div</value>
      <webElementGuid>4735beb9-3134-4b80-b4ce-a5b5aabfcaa3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '' or . = '')]</value>
      <webElementGuid>8ba9f2ce-70c7-4ee5-b123-58df510cbfd4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
