<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_orderorder</name>
   <tag></tag>
   <elementGuidId>45895e0b-ae37-4d5f-9a2a-d6d0a83231b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.ms-Breadcrumb-item.item-107 > div.ms-TooltipHost.root-110</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='gatsby-focus-wrapper']/div/main/div/div/div/div/div/div/ol/li[5]/span/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>863f8c89-2a34-4308-977a-a28ab77551ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ms-TooltipHost root-110</value>
      <webElementGuid>d6c04823-3bbe-4aa7-aa5b-25d527edd6b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>d94647ae-e5a3-43cc-8713-fa89a1c44457</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>orderorder</value>
      <webElementGuid>8a5c6dd3-22f8-4365-a0ef-0fda66add080</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gatsby-focus-wrapper&quot;)/div[@class=&quot;GenericLayout-module--container--9rlo1&quot;]/main[1]/div[@class=&quot;ms-Stack css-241&quot;]/div[1]/div[1]/div[1]/div[@class=&quot;ms-Breadcrumb root-100&quot;]/div[@class=&quot;ms-FocusZone css-108&quot;]/ol[@class=&quot;ms-Breadcrumb-list list-101&quot;]/li[@class=&quot;ms-Breadcrumb-listItem listItem-102&quot;]/span[@class=&quot;ms-Breadcrumb-item item-107&quot;]/div[@class=&quot;ms-TooltipHost root-110&quot;]</value>
      <webElementGuid>494ac491-866b-43af-a185-6a82b3c87de1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gatsby-focus-wrapper']/div/main/div/div/div/div/div/div/ol/li[5]/span/div</value>
      <webElementGuid>f4577d64-a5de-4e79-8336-5a7f08e62e61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='cabin'])[1]/following::div[1]</value>
      <webElementGuid>d3467a08-a4a3-4471-8732-a3ccf87412c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Order/Basket'])[1]/preceding::div[2]</value>
      <webElementGuid>0941fa77-3fe4-4591-a59b-45b8d56fe76e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='order']/parent::*</value>
      <webElementGuid>a3ebc108-7eba-492b-adb4-37d6978aeed2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div</value>
      <webElementGuid>9feec150-299f-4574-b4ab-767fbc8308bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'orderorder' or . = 'orderorder')]</value>
      <webElementGuid>1085fe0b-01b2-44c5-9c81-39139b117071</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
