<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_cabincabin</name>
   <tag></tag>
   <elementGuidId>dfc61644-6164-44d1-89c0-202d97e5a2d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.ms-Breadcrumb-item.item-107 > div.ms-TooltipHost.root-110</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='gatsby-focus-wrapper']/div/main/div/div/div/div/div/div/div/ol/li[4]/span/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>de51a407-ccda-4e3b-ac42-ec90025b9450</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ms-TooltipHost root-110</value>
      <webElementGuid>6ccd4de5-508d-4186-8896-4c8a37a580fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>8d15eaee-5419-455c-bad3-096a15b123a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>cabincabin</value>
      <webElementGuid>98e6fab6-3827-4a59-a746-d424344a5de2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gatsby-focus-wrapper&quot;)/div[@class=&quot;GenericLayout-module--container--9rlo1&quot;]/main[1]/div[@class=&quot;ms-Stack css-98&quot;]/div[@class=&quot;ms-StackItem css-99&quot;]/div[1]/div[1]/div[1]/div[@class=&quot;ms-Breadcrumb root-100&quot;]/div[@class=&quot;ms-FocusZone css-108&quot;]/ol[@class=&quot;ms-Breadcrumb-list list-101&quot;]/li[@class=&quot;ms-Breadcrumb-listItem listItem-102&quot;]/span[@class=&quot;ms-Breadcrumb-item item-107&quot;]/div[@class=&quot;ms-TooltipHost root-110&quot;]</value>
      <webElementGuid>c543593c-60a5-4231-bfd4-810afa1bff34</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gatsby-focus-wrapper']/div/main/div/div/div/div/div/div/div/ol/li[4]/span/div</value>
      <webElementGuid>3061909e-8666-47c3-988a-926470a200b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='sailing'])[1]/following::div[1]</value>
      <webElementGuid>5780e83c-bbae-4bec-a6dc-485b68b0e522</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cabins'])[1]/preceding::div[2]</value>
      <webElementGuid>0db3436a-0092-4bf3-9336-cac7fedf9d9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='cabin']/parent::*</value>
      <webElementGuid>c4a8714f-0f73-44cd-b920-97b5ef8409c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div</value>
      <webElementGuid>8fbff44d-cf1e-4f1f-9f4d-6e688062fc7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'cabincabin' or . = 'cabincabin')]</value>
      <webElementGuid>b59d80f6-05e5-4002-983e-c71cf9f8a485</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
