<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Passenger Ages</name>
   <tag></tag>
   <elementGuidId>e5764608-2ae7-4be8-b2f6-b997ad9f490a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='No. of Passengers'])[1]/following::h2[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>e71f5c0b-cd28-4115-b43a-f3645c0f1beb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>results-module--modal-headings--+5iOZ</value>
      <webElementGuid>ef1e1eec-3b17-41cc-9a0f-07af7c6fe1bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Passenger Ages</value>
      <webElementGuid>6393322d-9911-4344-903d-db76e2be268c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ModalFocusTrapZone835&quot;)/div[@class=&quot;ms-Modal-scrollableContent scrollableContent-204&quot;]/form[1]/div[@class=&quot;ms-Stack css-239&quot;]/div[@class=&quot;ms-Stack css-241&quot;]/div[@class=&quot;ms-Stack css-160&quot;]/div[@class=&quot;ms-Stack css-185&quot;]/h2[@class=&quot;results-module--modal-headings--+5iOZ&quot;]</value>
      <webElementGuid>6127b821-2d6f-46cb-bf9a-d53c3955f179</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>06198072-ebdd-46f0-85e1-be94490158bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>results-module--modal-headings--+5iOZ</value>
      <webElementGuid>03e7ecb6-8b3c-4339-a90f-3a58a5cf3746</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Passenger Ages</value>
      <webElementGuid>07cd8862-4494-4e86-b134-6ebab023281b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ModalFocusTrapZone817&quot;)/div[@class=&quot;ms-Modal-scrollableContent scrollableContent-204&quot;]/form[1]/div[@class=&quot;ms-Stack css-239&quot;]/div[@class=&quot;ms-Stack css-241&quot;]/div[@class=&quot;ms-Stack css-160&quot;]/div[@class=&quot;ms-Stack css-185&quot;]/h2[@class=&quot;results-module--modal-headings--+5iOZ&quot;]</value>
      <webElementGuid>f8733c01-1356-4bc4-8150-ed4c0636aaf3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ModalFocusTrapZone835']/div[2]/form/div/div[2]/div[2]/div/h2</value>
      <webElementGuid>f2647bc1-13c5-4557-986f-3557dced54a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No. of Passengers'])[1]/following::h2[1]</value>
      <webElementGuid>ea4381e4-2f51-4dfe-8f1c-43b4638917ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please fill out the following information for more accurate pricing'])[1]/following::h2[1]</value>
      <webElementGuid>1b5f58d7-5b94-4417-b4c3-86a1b6fa76b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Input age of passenger on return date.'])[1]/preceding::h2[1]</value>
      <webElementGuid>9c2106ea-97bf-40c9-ac63-cb1a20b9c055</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Passenger 1'])[1]/preceding::h2[1]</value>
      <webElementGuid>3dd0c979-b325-434a-a423-c9c595361a53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Passenger Ages']/parent::*</value>
      <webElementGuid>f28fe773-3895-4d32-9f2c-ef63128dadf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/h2</value>
      <webElementGuid>cff35a69-c8f4-4216-bab4-62d9cf5de3e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'Passenger Ages' or . = 'Passenger Ages')]</value>
      <webElementGuid>fcd330c0-c0f8-45c6-ae36-5120632e1df0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ModalFocusTrapZone817']/div[2]/form/div/div[2]/div[2]/div/h2</value>
      <webElementGuid>e559cfc2-a0b8-4254-9b4f-ed58f700f35f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
