<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_</name>
   <tag></tag>
   <elementGuidId>311e83d3-ed65-42b9-b0bc-659ffca916d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.ms-Icon.root-89.css-192</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='gatsby-focus-wrapper']/div/main/div/div[2]/div/ul/li/div/div[2]/div/div/div[2]/div/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>ec2ab39f-1642-4a0d-881c-8dd33c05618e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-icon-name</name>
      <type>Main</type>
      <value>CalendarDay</value>
      <webElementGuid>c7a4317b-0f21-4a17-98a6-9f6c0624e0d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>07e361a0-5348-496f-aa7d-37803f613079</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ms-Icon root-89 css-192</value>
      <webElementGuid>ec7e2a00-6185-4831-abe3-b0b2d49feeef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>235934ba-359f-4003-9ecc-6e43666af6c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gatsby-focus-wrapper&quot;)/div[@class=&quot;GenericLayout-module--container--9rlo1&quot;]/main[1]/div[@class=&quot;GridRow-module--grid-row--inJvQ GridRow-module--grid-row--padded--fWrJ3&quot;]/div[@class=&quot;GridColumn-module--grid-column--fqCL9 GridColumn-module--size-9--3CuBP GridColumn-module--grid-column--padded--TTiI2&quot;]/div[@class=&quot;ms-Stack css-160&quot;]/ul[@class=&quot;ResultsList-module--list--+ZCDo List-module--list-unstyled--OYpBm&quot;]/li[@class=&quot;ResultsListItem-module--container--3g6pa&quot;]/div[@class=&quot;ms-Stack css-185&quot;]/div[@class=&quot;ms-StackItem css-190&quot;]/div[@class=&quot;GridRow-module--grid-row--inJvQ&quot;]/div[@class=&quot;GridColumn-module--grid-column--fqCL9 GridColumn-module--size-auto--BIIV5&quot;]/div[@class=&quot;GridRow-module--grid-row--inJvQ GridRow-module--grid-row--padded--fWrJ3&quot;]/div[@class=&quot;DetailsSection-module--details-icons--P3sBi&quot;]/i[@class=&quot;ms-Icon root-89 css-192&quot;]</value>
      <webElementGuid>b9116526-ecb6-4e01-a350-1a92a23fb744</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>2e20b12b-babd-4b33-a2b3-bba1aa5df433</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-icon-name</name>
      <type>Main</type>
      <value>CheckMark</value>
      <webElementGuid>aa683f19-e115-4b12-b79b-07c2855df2c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d3e38ff6-5e99-4423-8fcb-fbb43baca636</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ms-Checkbox-checkmark checkmark-169</value>
      <webElementGuid>b1d8b459-06bf-4456-9f32-9eeeff11a907</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>12b1a0d7-692e-4585-83c9-e8bbabebb14b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cruise-line-filter-content&quot;)/div[@class=&quot;AccordionItem-module--item-spacing--Up8JF&quot;]/div[@class=&quot;ms-Stack css-162&quot;]/div[@class=&quot;ms-Checkbox is-enabled root-163&quot;]/label[@class=&quot;ms-Checkbox-label label-165&quot;]/div[@class=&quot;ms-Checkbox-checkbox checkbox-166&quot;]/i[@class=&quot;ms-Checkbox-checkmark checkmark-169&quot;]</value>
      <webElementGuid>2a6feaac-83b6-43bb-8c1c-85e9fe051bd9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gatsby-focus-wrapper']/div/main/div/div[2]/div/ul/li/div/div[2]/div/div/div[2]/div/i</value>
      <webElementGuid>4cfa3711-6032-4ad3-bd14-59b5c56c8dab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Northern Europe Andscandinavia'])[1]/following::i[1]</value>
      <webElementGuid>2209e58c-ce9f-433b-a5a6-c747171a0eae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(found: 980, showing: 980)'])[1]/following::i[1]</value>
      <webElementGuid>b78060bc-44ff-429c-922f-1049fcef1082</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Europe'])[1]/preceding::i[3]</value>
      <webElementGuid>32f97150-1f70-4e65-994e-250a96a896fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Queen Anne'])[1]/preceding::i[4]</value>
      <webElementGuid>4f3f63d2-12f4-4754-9a55-4e56ab89760d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='']/parent::*</value>
      <webElementGuid>ff0b4ce3-31a7-4b0b-8791-2d10f029fdde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/i</value>
      <webElementGuid>8c028a88-4b42-40e8-b9ec-e05a659c81f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[(text() = '' or . = '')]</value>
      <webElementGuid>8ef0b7e4-742a-4671-b94a-a3edfaf64cb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cruise-line-filter-content']/div/div/div[3]/label/div/i</value>
      <webElementGuid>fb74d9c3-1289-40e7-9579-7afe1acfec45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Holland America (159)'])[1]/following::i[1]</value>
      <webElementGuid>9be4d25c-31ee-4381-bb31-dbdeab63895f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cunard (354)'])[1]/following::i[2]</value>
      <webElementGuid>44573ee7-1dc5-47c1-941f-015e9440496b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Princess (201)'])[1]/preceding::i[1]</value>
      <webElementGuid>a3d4c75d-d1f8-4c9c-8646-a586c06da543</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Seabourn (265)'])[1]/preceding::i[2]</value>
      <webElementGuid>6ec608c2-0ee4-45ae-9bc0-30319d01004d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/label/div/i</value>
      <webElementGuid>234f46d0-22bb-467e-a5d0-efa59aa62116</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[(text() = '' or . = '')]</value>
      <webElementGuid>cc888884-5b70-40f7-a467-d95bdb08523c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
