<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_</name>
   <tag></tag>
   <elementGuidId>311e83d3-ed65-42b9-b0bc-659ffca916d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cruise-line-filter-content']/div/div/div[3]/label/div/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>2e20b12b-babd-4b33-a2b3-bba1aa5df433</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-icon-name</name>
      <type>Main</type>
      <value>CheckMark</value>
      <webElementGuid>aa683f19-e115-4b12-b79b-07c2855df2c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d3e38ff6-5e99-4423-8fcb-fbb43baca636</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ms-Checkbox-checkmark checkmark-169</value>
      <webElementGuid>b1d8b459-06bf-4456-9f32-9eeeff11a907</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>12b1a0d7-692e-4585-83c9-e8bbabebb14b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cruise-line-filter-content&quot;)/div[@class=&quot;AccordionItem-module--item-spacing--Up8JF&quot;]/div[@class=&quot;ms-Stack css-162&quot;]/div[@class=&quot;ms-Checkbox is-enabled root-163&quot;]/label[@class=&quot;ms-Checkbox-label label-165&quot;]/div[@class=&quot;ms-Checkbox-checkbox checkbox-166&quot;]/i[@class=&quot;ms-Checkbox-checkmark checkmark-169&quot;]</value>
      <webElementGuid>2a6feaac-83b6-43bb-8c1c-85e9fe051bd9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cruise-line-filter-content']/div/div/div[3]/label/div/i</value>
      <webElementGuid>fb74d9c3-1289-40e7-9579-7afe1acfec45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Holland America (159)'])[1]/following::i[1]</value>
      <webElementGuid>9be4d25c-31ee-4381-bb31-dbdeab63895f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cunard (354)'])[1]/following::i[2]</value>
      <webElementGuid>44573ee7-1dc5-47c1-941f-015e9440496b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Princess (201)'])[1]/preceding::i[1]</value>
      <webElementGuid>a3d4c75d-d1f8-4c9c-8646-a586c06da543</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Seabourn (265)'])[1]/preceding::i[2]</value>
      <webElementGuid>6ec608c2-0ee4-45ae-9bc0-30319d01004d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/label/div/i</value>
      <webElementGuid>234f46d0-22bb-467e-a5d0-efa59aa62116</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[(text() = '' or . = '')]</value>
      <webElementGuid>cc888884-5b70-40f7-a467-d95bdb08523c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
