<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i__1_2_3_4_5_6_7</name>
   <tag></tag>
   <elementGuidId>22a21449-c177-475d-860c-4547380ec65b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.ms-Icon.root-90.css-112.ms-Button-icon.icon-119</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='gatsby-focus-wrapper']/div/main/div/div[4]/div[2]/div[2]/div/div[2]/div/button/span/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>5f3f5837-b9bd-4832-b202-08d0f584fe68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-icon-name</name>
      <type>Main</type>
      <value>Edit</value>
      <webElementGuid>680a4eed-21ea-4006-99bb-46e413c66012</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ddb169f4-bce0-4f3a-b450-0a25bd580fd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ms-Icon root-90 css-112 ms-Button-icon icon-119</value>
      <webElementGuid>be38de02-80ae-48ba-82cc-e20d28c94d72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>4248885f-7d64-4162-ad5f-2815ae8554f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gatsby-focus-wrapper&quot;)/div[@class=&quot;GenericLayout-module--container--9rlo1&quot;]/main[1]/div[@class=&quot;ms-Stack css-241&quot;]/div[@class=&quot;ms-Stack css-243&quot;]/div[@class=&quot;ms-Stack css-241&quot;]/div[@class=&quot;ms-StackItem css-115&quot;]/div[@class=&quot;ms-Stack css-263&quot;]/div[@class=&quot;ms-Stack css-265&quot;]/div[@class=&quot;ms-Stack css-266&quot;]/button[@class=&quot;ms-Button ms-Button--icon root-214&quot;]/span[@class=&quot;ms-Button-flexContainer flexContainer-117&quot;]/i[@class=&quot;ms-Icon root-90 css-112 ms-Button-icon icon-119&quot;]</value>
      <webElementGuid>f7101a35-7d0d-4845-888d-a3f21bf959ca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gatsby-focus-wrapper']/div/main/div/div[4]/div[2]/div[2]/div/div[2]/div/button/span/i</value>
      <webElementGuid>48a90b58-2d4b-474a-8f47-cbe9aa23db56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lead Passenger'])[1]/following::i[1]</value>
      <webElementGuid>085b288a-c26d-4ef0-9ee7-27ee4769707a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Passenger Summary'])[1]/following::i[1]</value>
      <webElementGuid>e75a035b-4769-431c-bbba-c32426f2b84f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Passenger 2'])[1]/preceding::i[1]</value>
      <webElementGuid>71d50baa-2ca1-4965-b646-13a537bd4b61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='']/parent::*</value>
      <webElementGuid>c7693f22-e7ab-4d2a-bbd5-dc8214296e3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/button/span/i</value>
      <webElementGuid>5257bd30-f692-4284-84eb-f0fc0a38bb5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[(text() = '' or . = '')]</value>
      <webElementGuid>171b3d87-6a5a-4819-950e-c864cc298dc6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
