<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i__1_2_3_4</name>
   <tag></tag>
   <elementGuidId>a36f0a26-ceac-4331-a943-9c1049e605ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cruise-line-filter-content']/div/div/div[3]/label/div/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>b16496b9-f540-4e95-aace-9c1a9f27e81d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-icon-name</name>
      <type>Main</type>
      <value>CheckMark</value>
      <webElementGuid>e5a566a4-be5a-4220-874b-de758c3082c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>17337d44-2a7a-4279-a435-2460972a17bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ms-Checkbox-checkmark checkmark-169</value>
      <webElementGuid>eb959e0d-c1f4-4ce3-a9c9-4de64c62b4b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>2bb9f3e9-4001-41a1-a587-cfe16406db7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cruise-line-filter-content&quot;)/div[@class=&quot;AccordionItem-module--item-spacing--Up8JF&quot;]/div[@class=&quot;ms-Stack css-162&quot;]/div[@class=&quot;ms-Checkbox is-enabled root-163&quot;]/label[@class=&quot;ms-Checkbox-label label-165&quot;]/div[@class=&quot;ms-Checkbox-checkbox checkbox-166&quot;]/i[@class=&quot;ms-Checkbox-checkmark checkmark-169&quot;]</value>
      <webElementGuid>81000377-d967-45d2-ba91-4c9b26e95406</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cruise-line-filter-content']/div/div/div[3]/label/div/i</value>
      <webElementGuid>25ed5bce-26d0-4710-997b-0df4c5a6f1e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Holland America (159)'])[1]/following::i[1]</value>
      <webElementGuid>bc0af7e8-60f1-4a6f-a787-1b543ef509f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cunard (353)'])[1]/following::i[2]</value>
      <webElementGuid>16f55457-4538-4b6a-b166-6887e1ac949a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Princess (201)'])[1]/preceding::i[1]</value>
      <webElementGuid>6a0ce6ce-7062-4c53-ac51-78d2c2d8b9c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Seabourn (267)'])[1]/preceding::i[2]</value>
      <webElementGuid>7e8b1230-b934-4f7e-9d33-2b698b661e34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/label/div/i</value>
      <webElementGuid>49c01a25-a03c-4c0b-8560-cef5a97a3b3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[(text() = '' or . = '')]</value>
      <webElementGuid>be1c1d09-78c9-4372-a217-f452ed582a80</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
