<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Destination_destination-auto-suggest-input</name>
   <tag></tag>
   <elementGuidId>0947416a-5928-4627-8fc9-372da2e6dec4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='destination-auto-suggest-input']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#destination-auto-suggest-input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4d7e70a4-f6f2-46bd-9f3a-bcb58a5af338</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fdfb7790-354a-477f-a210-9d894383df4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>destination-auto-suggest-input</value>
      <webElementGuid>d17efd7d-b2eb-4f27-97cc-89e6bb8bd587</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Any...</value>
      <webElementGuid>75554b45-ccd7-4a7f-8abb-00c6507034ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>223c1361-fa22-40dd-a718-14b7d481ec47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>a1419a39-8fff-4bc2-aafb-8149a84eb923</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>react-autowhatever-1</value>
      <webElementGuid>1179bc9a-8f75-45cc-bf8b-17ed2dcaec5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ms-TextField-field field-158</value>
      <webElementGuid>6598ae9c-36ac-41c8-9353-e64812ea8c8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>TextFieldLabel2</value>
      <webElementGuid>300e999a-2eba-4d21-92ca-db8f6313abcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ce1c028b-01d4-4e31-aae6-ca023cf6f199</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;destination-auto-suggest-input&quot;)</value>
      <webElementGuid>e6b14ab8-70e8-488f-95aa-1df4b35cea9f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='destination-auto-suggest-input']</value>
      <webElementGuid>16ee81b4-d976-4ee5-a118-29fda746089d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gatsby-focus-wrapper']/div/main/form/div/div/div/div/div/div/div/input</value>
      <webElementGuid>8166463f-5f37-4202-8996-29bb3f4aafc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>0b689519-3b0c-460c-9fe6-58de1f8a259f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'destination-auto-suggest-input' and @placeholder = 'Any...']</value>
      <webElementGuid>93aed0f9-26ec-4774-9c37-11c9e8d0cc48</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
