<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Guaranteed Cabin_GUAR-cabin-radio</name>
   <tag></tag>
   <elementGuidId>d1704cca-925f-4c4c-bb8a-d9ede571322d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#GUAR-cabin-radio</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='GUAR-cabin-radio']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e5f875d1-10fe-4fb2-b4c5-25b6a18464b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>GUAR-cabin-radio</value>
      <webElementGuid>0e5288b0-ba40-4327-b29c-88435ac8094c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>c5ba96e3-483f-4c0b-97f2-5763742c2f8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>GUAR</value>
      <webElementGuid>078f24a6-03c0-4044-a822-e67319143c2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;GUAR-cabin-radio&quot;)</value>
      <webElementGuid>8f0fe884-bb56-4638-8128-7082b4940a84</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='GUAR-cabin-radio']</value>
      <webElementGuid>d312b6b8-53ed-4ad1-8621-84b2e76d7dbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gatsby-focus-wrapper']/div/main/div/div/form/fieldset/div/table/tbody/tr/td[3]/input</value>
      <webElementGuid>a00f15ff-5fcb-474b-82f0-756266a99eae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>9a918dd1-568d-4dd5-b855-28b2bbbf738b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'GUAR-cabin-radio' and @type = 'radio']</value>
      <webElementGuid>cf320a41-48c6-4ab7-bc25-b1570bfafa00</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
