<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Bedding Options</name>
   <tag></tag>
   <elementGuidId>20faf1ed-b6cc-4811-8bff-1dca1042bd1c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#bedding-input-label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='bedding-input-label']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>98be7230-8335-4592-a596-30271844243f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ms-Label ms-Dropdown-label root-181</value>
      <webElementGuid>ca7331ea-e778-4f55-ac20-0363f08fcda4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bedding-input-label</value>
      <webElementGuid>f687d291-47d7-4b3a-9ac0-890a2ab6b788</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bedding Options</value>
      <webElementGuid>0d40536b-13c9-418d-8cd9-de5d9c550243</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bedding-input-label&quot;)</value>
      <webElementGuid>780ddf39-0a1b-4d65-8d56-28cd00efc45a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='bedding-input-label']</value>
      <webElementGuid>80d2d182-23ea-46b9-be20-579bb4d6d395</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gatsby-focus-wrapper']/div/main/div/div/form/div[2]/div/div/div[2]/label</value>
      <webElementGuid>f680169b-7f46-42fe-9e92-2ffd49b6ba2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bedding'])[1]/following::label[1]</value>
      <webElementGuid>f236cd2a-c7e0-4d81-81f3-c60faffe5d93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='port, aft, oceanview'])[1]/following::label[1]</value>
      <webElementGuid>e7fbd97c-c7f2-4288-b65d-f026ef307746</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select bedding'])[1]/preceding::label[1]</value>
      <webElementGuid>3f532c15-4538-4862-85ae-96deb612f2f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dining'])[1]/preceding::label[1]</value>
      <webElementGuid>ec43afdd-a750-4a9b-8b4e-bc60f9032e48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Bedding Options']/parent::*</value>
      <webElementGuid>0484dd0a-7155-445b-baed-68338dd11be3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/label</value>
      <webElementGuid>85d4ae9d-1008-488e-adfd-a96a6ae5c83c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'bedding-input-label' and (text() = 'Bedding Options' or . = 'Bedding Options')]</value>
      <webElementGuid>29ecce96-d91c-422c-840d-4dc9ad0b1107</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
