<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Special Requests</name>
   <tag></tag>
   <elementGuidId>b1208400-81ad-4985-bca5-0627f7476da1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#TextFieldLabel16</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='TextFieldLabel16']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>ce08d4ac-7c65-4034-965c-500b126ce294</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>special-request-input</value>
      <webElementGuid>fe9cb9b0-2983-4db5-b3ec-5e810b64a68d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TextFieldLabel16</value>
      <webElementGuid>64c67dcc-78ed-4dd5-8a79-c3f6c9731fc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ms-Label root-194</value>
      <webElementGuid>2a84aa3c-d4ce-4410-9a86-137207cc4584</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Special Requests</value>
      <webElementGuid>313d82d1-694f-4799-9d33-efff7abbfb9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TextFieldLabel16&quot;)</value>
      <webElementGuid>39e0822a-8199-4449-85d3-c2c452043a66</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='TextFieldLabel16']</value>
      <webElementGuid>c2cbbac4-a6ad-4824-9f8d-fcd4dfbeee2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gatsby-focus-wrapper']/div/main/div/div/form/div[2]/div/div[7]/div/div/label</value>
      <webElementGuid>0df65f54-c650-487e-8d50-fcf546dacb66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(optional)'])[1]/following::label[1]</value>
      <webElementGuid>13d54f2a-977e-4696-9a25-d610c148057a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Special Requests'])[1]/following::label[1]</value>
      <webElementGuid>1ac968ab-384b-4b55-914b-86337ccded10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirm'])[1]/preceding::label[1]</value>
      <webElementGuid>1668f323-1edd-4da8-8ba2-279fb96463f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deck Dolphin - Dolphin'])[1]/preceding::label[1]</value>
      <webElementGuid>b2ea34f4-1dee-4ee9-a5b7-6ed6da062d40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/label</value>
      <webElementGuid>1f797924-dd41-42cf-9606-835f45831e6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'TextFieldLabel16' and (text() = 'Special Requests' or . = 'Special Requests')]</value>
      <webElementGuid>ef75e1e3-a2a6-4544-99fb-86c9bd0d5d9a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
