<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Departure Start Date</name>
   <tag></tag>
   <elementGuidId>bfb202c8-00db-4b3b-a2af-2038836bfa34</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='TextFieldLabel9']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#TextFieldLabel9</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>4d3cf95b-a2a4-43e3-8bd9-9ed6d806c8ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>DatePicker5-label</value>
      <webElementGuid>6490324b-fc64-4db7-9f25-ce6eeff2a319</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TextFieldLabel9</value>
      <webElementGuid>f595ecc5-3ba2-4ab5-90b1-32ec6cf40752</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ms-Label root-114</value>
      <webElementGuid>5ef98c88-4e4b-4cab-b3bb-9864d4f86710</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Departure Start Date</value>
      <webElementGuid>68c0528f-9275-49c4-8bab-9ebece24ff79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TextFieldLabel9&quot;)</value>
      <webElementGuid>d562416b-b74f-4142-b62f-ded60991141a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='TextFieldLabel9']</value>
      <webElementGuid>3fe9e8e0-f10b-49b5-8021-c5423beaba07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gatsby-focus-wrapper']/div/main/form/div/div/div[2]/div/div/div/div/label</value>
      <webElementGuid>6303ac77-f414-4c39-97bf-2443787a0ddd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Destination'])[1]/following::label[1]</value>
      <webElementGuid>6e57ad0e-8d62-4c4a-923f-a605f133c9ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Traveltek Cruise Search'])[1]/following::label[2]</value>
      <webElementGuid>996cc4c6-6ce2-4e19-a6c3-138304cecf54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thu Sep 01 2022'])[1]/preceding::label[1]</value>
      <webElementGuid>eee42bdf-521e-49f7-b801-60ae6794751f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Departure End Date'])[1]/preceding::label[1]</value>
      <webElementGuid>991a1507-3a37-4d70-939d-4879a63b6836</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Departure Start Date']/parent::*</value>
      <webElementGuid>21e00f5a-bcc5-4102-9f2b-1df3670db046</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/label</value>
      <webElementGuid>05d9db6a-8730-440c-b418-c1fb095bfbdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'TextFieldLabel9' and (text() = 'Departure Start Date' or . = 'Departure Start Date')]</value>
      <webElementGuid>4804e319-5615-4955-b853-372f6da4f11a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
