<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_No. of Passengers</name>
   <tag></tag>
   <elementGuidId>53a358e3-35f1-4db5-81bc-3a5c59ea2df9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='Dropdown3000-label']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Dropdown3000-label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>afbdf8b0-ea9e-4e89-9c7d-398789c15f16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ms-Label ms-Dropdown-label label-244</value>
      <webElementGuid>dffdc313-dd94-4736-a13f-3ee7e684400a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Dropdown3000-label</value>
      <webElementGuid>f36ffdcf-8a08-48a4-978d-c6625907a6ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>No. of Passengers</value>
      <webElementGuid>4bb888fb-69c5-4b24-82a1-561e83ca8236</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Dropdown3000-label&quot;)</value>
      <webElementGuid>ab23579f-ff5a-4be7-906f-3150bf2a734a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='Dropdown3000-label']</value>
      <webElementGuid>4dc06e54-fe40-43a6-89b4-e24c18e8be73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ModalFocusTrapZone817']/div[2]/form/div/div[2]/div/label</value>
      <webElementGuid>f2da4613-b585-456f-955b-23d227c5cc60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please fill out the following information for more accurate pricing'])[1]/following::label[1]</value>
      <webElementGuid>6cd6d7a0-743a-46f5-82a2-0792f15c1262</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Passenger Information'])[1]/following::label[1]</value>
      <webElementGuid>49422b9f-4b36-4147-a6a0-944bf08decf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Passenger Ages'])[1]/preceding::label[1]</value>
      <webElementGuid>695bafc0-963b-4e30-9943-b5cd2eb98a52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Input age of passenger on return date.'])[1]/preceding::label[1]</value>
      <webElementGuid>7e1fc976-8cbf-43d6-a262-c770a7fd56da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='No. of Passengers']/parent::*</value>
      <webElementGuid>b7067958-d54f-4e7f-b5e4-a88741efe878</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/label</value>
      <webElementGuid>cd2c9c13-3065-49aa-9bca-a806cdec116c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'Dropdown3000-label' and (text() = 'No. of Passengers' or . = 'No. of Passengers')]</value>
      <webElementGuid>a61d69c4-bb38-4686-a9da-3538cede27ec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
