<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Deck</name>
   <tag></tag>
   <elementGuidId>68d64257-e79b-4c20-b345-55ba29889d20</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#header11-cabinDeck</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='header11-cabinDeck']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e0c3a4b5-df24-448e-b9ac-fb2a4d3cfadf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>header11-cabinDeck</value>
      <webElementGuid>a973ecc7-8e92-4305-a0ad-a330d8b842b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ms-DetailsHeader-cellTitle cellTitle-173</value>
      <webElementGuid>3b10b0b4-fa64-4c0a-8bdf-e1fc4f9013d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Deck</value>
      <webElementGuid>1f92361d-0f4f-4cbd-8a74-9e833f039c51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header11-cabinDeck&quot;)</value>
      <webElementGuid>7141453a-195a-4c82-af64-ee62846b9d8f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='header11-cabinDeck']</value>
      <webElementGuid>93059bbd-f643-4387-b732-06946d2f7b97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gatsby-focus-wrapper']/div/main/div/div/form/fieldset/div[7]/div/div/div/div/div[3]/span/span</value>
      <webElementGuid>75254335-d690-4f97-84ac-3b9fd4c1b0e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cabin'])[2]/following::span[2]</value>
      <webElementGuid>7f24e45a-cd54-4093-88a0-2dc7f2797c97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Deck'])[1]/following::span[7]</value>
      <webElementGuid>331a2e8e-2b25-43f5-8d62-3adde98bf891</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Location'])[1]/preceding::span[2]</value>
      <webElementGuid>b6ef65a8-b8ec-4d7a-8033-af96243769ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/span/span</value>
      <webElementGuid>b11b8dc3-1836-4f83-ab73-c1ab41fe7865</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'header11-cabinDeck' and (text() = 'Deck' or . = 'Deck')]</value>
      <webElementGuid>9c5f7134-4078-4b92-95b6-7aef797f11aa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
