<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Pricing Information_1</name>
   <tag></tag>
   <elementGuidId>67f8b4d7-2034-40b3-b4c0-7b2964abee8e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#id__119</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='gatsby-focus-wrapper']/div/main/div/div[4]/div/div/div[4]/div/button/span/span/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c3e9c328-ba3e-46d3-b55d-de5273cceba5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ms-Button-label label-120</value>
      <webElementGuid>acaeaa1c-5c9e-4774-96ae-47f756c7329e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id__119</value>
      <webElementGuid>70d82abb-a0e8-40bb-a4fc-8bcad60791e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pricing Information</value>
      <webElementGuid>b9c47878-1b51-4157-8f17-6e49b33ef7df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id__119&quot;)</value>
      <webElementGuid>b8238aa4-04ef-4c80-8d2d-b5a3ed56d7bc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='id__119']</value>
      <webElementGuid>5b3a186b-8dd4-43dd-89c0-c3cecdfe0df0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gatsby-focus-wrapper']/div/main/div/div[4]/div/div/div[4]/div/button/span/span/span</value>
      <webElementGuid>00789512-30b2-43a5-b757-e3d8bf9e9b0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Refresh'])[1]/following::span[3]</value>
      <webElementGuid>1461422a-6181-4126-9a8a-9346ab708695</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancellation Policy'])[1]/preceding::span[1]</value>
      <webElementGuid>3df70065-be3e-4abf-9b86-f2617ded1d6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Summary'])[1]/preceding::span[4]</value>
      <webElementGuid>e8f7819e-a629-4685-9a22-0641b006a896</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pricing Information']/parent::*</value>
      <webElementGuid>bc84fd2e-d8e4-4336-8d73-2a71248b885a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span</value>
      <webElementGuid>f40a792a-41ce-4b30-a9b5-9b842dec94ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'id__119' and (text() = 'Pricing Information' or . = 'Pricing Information')]</value>
      <webElementGuid>a6122e37-9cde-4374-8857-6a944bc542ef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
