<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Select dining option</name>
   <tag></tag>
   <elementGuidId>f81caa96-a986-43d8-a1a8-50a0bd318d96</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dining-input-option</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='dining-input-option']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>afe7cb6d-ecf7-4bbf-8091-290fe4adc4a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dining-input-option</value>
      <webElementGuid>717c732b-3a6c-4c92-a3e1-e3b20a18e848</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ms-Dropdown-title ms-Dropdown-titleIsPlaceHolder title-130</value>
      <webElementGuid>5ba23907-013c-4913-b00d-571c91f812cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c4aa5de9-c3a2-420f-9ec9-877cba25b5e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-live</name>
      <type>Main</type>
      <value>polite</value>
      <webElementGuid>c12c3041-f6d8-497f-b453-a9ec9e948078</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-atomic</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>60a8eaef-f717-41eb-8f13-7f27c7882fe3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select dining option</value>
      <webElementGuid>4915c6ef-d22b-4337-800b-7d1de83a5cd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dining-input-option&quot;)</value>
      <webElementGuid>2fcbf75b-1291-44bf-a5be-5e02b8b67c6c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='dining-input-option']</value>
      <webElementGuid>e757a988-08f4-48be-aa7d-e9b6a32cee77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dining-input']/span</value>
      <webElementGuid>005634a7-3f15-4766-9887-4185370a8288</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dining Options'])[1]/following::span[1]</value>
      <webElementGuid>521574f7-9276-4fd6-9f43-04a9f520fcb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dining'])[1]/following::span[1]</value>
      <webElementGuid>dbc27128-6cbb-4bd4-a2f8-c907b9b3fb19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Special Requests'])[1]/preceding::span[2]</value>
      <webElementGuid>84d58414-b45b-4a7e-9224-9b499eb41b22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(optional)'])[1]/preceding::span[3]</value>
      <webElementGuid>46df265b-c3b5-453e-a28e-ad80970bdf9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Select dining option']/parent::*</value>
      <webElementGuid>30003fdd-3788-4d10-b0b2-4066f966c02a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/span</value>
      <webElementGuid>819c6a5b-e985-44b5-b164-738fdac6c2ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'dining-input-option' and (text() = 'Select dining option' or . = 'Select dining option')]</value>
      <webElementGuid>79200991-0f68-4450-8266-abd647320924</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
