<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Obstruction</name>
   <tag></tag>
   <elementGuidId>a5444a78-3a8e-4ce2-80a0-ada1bc0d5c2d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#header11-cabinObstructed-name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='header11-cabinObstructed-name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>37b68917-2725-4a89-8a73-070895e73554</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>header11-cabinObstructed-name</value>
      <webElementGuid>b3586bd4-ef01-4ba9-83a5-513449ee3d00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ms-DetailsHeader-cellName cellName-174</value>
      <webElementGuid>77aabb2c-4898-4dfb-85ac-84b3f3048898</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Obstruction</value>
      <webElementGuid>64b877a6-fa48-42fd-8dbd-c52664215538</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header11-cabinObstructed-name&quot;)</value>
      <webElementGuid>709021e4-557b-4526-9b46-47960e7f076d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='header11-cabinObstructed-name']</value>
      <webElementGuid>182ce9c1-8d8c-4c7a-aa9e-11ff0c9ca059</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='header11-cabinObstructed']/span</value>
      <webElementGuid>9a1b7117-a944-410d-ad6d-3acf1e731305</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Location'])[1]/following::span[3]</value>
      <webElementGuid>4086a3e2-ea04-41f6-b42b-28b485c7a355</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deck'])[1]/following::span[6]</value>
      <webElementGuid>ec8684c3-8bad-4cc4-bbab-7b120e337d4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Accessibility'])[1]/preceding::span[1]</value>
      <webElementGuid>d0b1e0f7-e4e7-43b5-89e2-bed4cb0954a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='D726'])[1]/preceding::span[5]</value>
      <webElementGuid>6e73aa71-38b3-4318-8fae-e797231bedaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Obstruction']/parent::*</value>
      <webElementGuid>35a9a335-289e-4610-abec-5ee679d7bfba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/span/span/span</value>
      <webElementGuid>2cc2adfb-0bc3-4218-a62b-46cbe7b6c427</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'header11-cabinObstructed-name' and (text() = 'Obstruction' or . = 'Obstruction')]</value>
      <webElementGuid>f628c820-d30e-4e96-be67-db85c494a5f6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
