<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_TWINS</name>
   <tag></tag>
   <elementGuidId>b8d83f1b-f0d2-44c2-a105-6fc2d6ad83a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[(text() = 'TWINS' or . = 'TWINS')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.ms-Button-flexContainer.flexContainer-230</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3fc67175-82c7-4f61-b315-6c77542bc0a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ms-Button-flexContainer flexContainer-230</value>
      <webElementGuid>73845ec6-447c-4bf6-b41d-fb5a9c2b777d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automationid</name>
      <type>Main</type>
      <value>splitbuttonprimary</value>
      <webElementGuid>83836481-1d24-48fe-a4a5-02e6b3d14a8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>TWINS</value>
      <webElementGuid>7cd93e69-8dcd-4727-a30b-019f79104bd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bedding-input-list0&quot;)/span[@class=&quot;ms-Button-flexContainer flexContainer-230&quot;]</value>
      <webElementGuid>00166b0f-041a-427b-8951-9dcd3948f8a4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='bedding-input-list0']/span</value>
      <webElementGuid>bb8cbd84-b060-4ebb-ae69-dd8dbd97f416</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deck Dolphin - Dolphin'])[1]/following::span[1]</value>
      <webElementGuid>b6b852aa-8dc9-4a12-a1f8-51eff204bd57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirm'])[1]/following::span[1]</value>
      <webElementGuid>dca99af8-2243-47ad-ba9f-0d690004139e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='QUEEN'])[1]/preceding::span[2]</value>
      <webElementGuid>e4b722f8-8dc7-4570-b15a-441a1301f851</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/div/div/button/span</value>
      <webElementGuid>1c0032df-17a8-41e2-8ab4-dc341501252e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'TWINS' or . = 'TWINS')]</value>
      <webElementGuid>3b901ee2-deb5-4204-b569-e82fa3a1652c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
