<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Cancellation Policy</name>
   <tag></tag>
   <elementGuidId>061d45e9-75e0-4146-b9ba-e65c85a2e1e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#id__122</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='gatsby-focus-wrapper']/div/main/div/div[4]/div/div/div[4]/div/button[2]/span/span/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e7df7c13-3ec2-44ca-87b4-b879d983d18c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ms-Button-label label-120</value>
      <webElementGuid>c4248a1c-98dc-4372-8f6b-3ea4ff38131e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id__122</value>
      <webElementGuid>4c3bd60f-db0a-41b3-b89b-91429608e044</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cancellation Policy</value>
      <webElementGuid>6d832210-c2a4-4d65-af59-0814e6392d82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id__122&quot;)</value>
      <webElementGuid>3523ead8-4fc8-4b09-b152-7654dd580cba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='id__122']</value>
      <webElementGuid>17b82c80-915e-44fb-b172-a41e932adb6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gatsby-focus-wrapper']/div/main/div/div[4]/div/div/div[4]/div/button[2]/span/span/span</value>
      <webElementGuid>a9f95f6a-ade2-4163-b89f-6e02b09ed09c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pricing Information'])[1]/following::span[3]</value>
      <webElementGuid>fbc3ae12-9563-40f5-be24-1f7e9026b3d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Refresh'])[1]/following::span[6]</value>
      <webElementGuid>a1e543ce-147a-44e2-bb82-7a4465086546</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Summary'])[1]/preceding::span[1]</value>
      <webElementGuid>db084d2f-e9dd-4724-8a7b-fc48a4c6a4f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Caribbean Cruise'])[2]/preceding::span[2]</value>
      <webElementGuid>15316d6f-5cb0-4799-981a-36272cb5779f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cancellation Policy']/parent::*</value>
      <webElementGuid>07c97df8-437c-43e2-a7ce-088eeb7eab26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]/span/span/span</value>
      <webElementGuid>a8b98c2d-af98-42de-b3ad-9ca06be1d155</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'id__122' and (text() = 'Cancellation Policy' or . = 'Cancellation Policy')]</value>
      <webElementGuid>900e45cf-a244-40fb-8e66-7fa3e03e0d65</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
