<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Grades</name>
   <tag></tag>
   <elementGuidId>e8d8b68e-70d2-4b36-b2db-e2d1a8f831ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.ms-Pivot-text.text-127</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='View Passenger Info'])[1]/following::span[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>656bb0b0-8789-4ca5-a9aa-c0acc7ce748e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ms-Pivot-text text-127</value>
      <webElementGuid>9a0baa00-46e1-4dd2-aa7f-317c496089ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Grades</value>
      <webElementGuid>8f84228f-cd31-4671-bbe1-6ada36e3c55c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Pivot7-Tab0&quot;)/span[@class=&quot;ms-Button-flexContainer flexContainer-130&quot;]/span[@class=&quot;ms-Pivot-linkContent linkContent-126&quot;]/span[@class=&quot;ms-Pivot-text text-127&quot;]</value>
      <webElementGuid>30ff6e60-8065-4c7c-ae64-2cba06d4a40d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='Pivot7-Tab0']/span/span/span</value>
      <webElementGuid>c6938915-0d95-4c81-8cca-bc385328e87e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View Passenger Info'])[1]/following::span[3]</value>
      <webElementGuid>a2678818-bcdb-47f1-9241-6034be39e8b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Regal Princess'])[1]/following::span[6]</value>
      <webElementGuid>3d6cf063-5479-4642-9340-7e8926f22203</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cabin Grade'])[1]/preceding::span[5]</value>
      <webElementGuid>a3072aa3-52a4-4b51-a795-35afd8510a84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Grades']/parent::*</value>
      <webElementGuid>e2a1d212-ad01-4081-b3ca-ef196aa80249</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/button/span/span/span</value>
      <webElementGuid>84a66c6b-a91a-4953-86f3-b77df00cd8ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' Grades' or . = ' Grades')]</value>
      <webElementGuid>7166c95c-a5f2-4346-b92e-d8ac94e46df7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
