<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Cabin</name>
   <tag></tag>
   <elementGuidId>eb09eaf4-27d5-4728-9c59-4d73f0ffaa19</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#header11-cabin-name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='header11-cabin-name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7e74a430-f4ce-4c7f-9c52-8139737a43cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>header11-cabin-name</value>
      <webElementGuid>6e45fe44-e1c7-48ad-a192-41b5af6317a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ms-DetailsHeader-cellName cellName-174</value>
      <webElementGuid>606c1f25-3c29-4024-b8d9-08a0b1cdad27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cabin</value>
      <webElementGuid>d9b69a1e-bfdc-4065-943a-a22ace4583d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header11-cabin-name&quot;)</value>
      <webElementGuid>4fe04c0e-68f1-477c-aaa3-ba28512799d7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='header11-cabin-name']</value>
      <webElementGuid>4d19c37e-ef41-4e88-8ac7-3e45191547c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='header11-cabin']/span</value>
      <webElementGuid>7a371315-f323-4757-8222-b864846a351f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Deck'])[1]/following::span[5]</value>
      <webElementGuid>da46ed8d-74b3-4bd1-bb65-4229aa8d77a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Cabin'])[1]/following::span[6]</value>
      <webElementGuid>67d9dcee-c6b9-4539-8d63-a2cd5b9dbba2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deck'])[1]/preceding::span[1]</value>
      <webElementGuid>f31bc572-3ddd-4f00-8727-725590133076</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Location'])[1]/preceding::span[4]</value>
      <webElementGuid>1ac4af6a-1b65-4f50-9404-216c6e8b667f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span/span/span</value>
      <webElementGuid>2477ed19-1516-40d9-b46d-212714a78cb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'header11-cabin-name' and (text() = 'Cabin' or . = 'Cabin')]</value>
      <webElementGuid>8110f91e-7bd4-4ac6-aa28-8c971604e3cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
