<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Select bedding</name>
   <tag></tag>
   <elementGuidId>f6f861c0-27fa-446a-8807-1e6e3950905b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#bedding-input-option</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='bedding-input-option']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e03d6ebf-abde-4c50-b9f9-8400b9c3f0f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bedding-input-option</value>
      <webElementGuid>3dee88c5-9948-4812-9097-502fc93b66a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ms-Dropdown-title ms-Dropdown-titleIsPlaceHolder title-130</value>
      <webElementGuid>f738204b-47ab-40a2-be48-efa37fa92703</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>35d2015e-b8ba-48c9-b5d7-0e9cfe96040c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-live</name>
      <type>Main</type>
      <value>polite</value>
      <webElementGuid>86d77db5-41ec-4bd4-b08c-bd379172b10d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-atomic</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>31b515b7-6885-4f6f-a5be-13d5c51d000d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select bedding</value>
      <webElementGuid>652b6e56-3e34-4ce0-9e3f-ff94a7fc19d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bedding-input-option&quot;)</value>
      <webElementGuid>ce5817a0-4fe9-4816-8847-75357d993b8f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='bedding-input-option']</value>
      <webElementGuid>075142ae-96d8-4278-8f3c-6f6783ab8357</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bedding-input']/span</value>
      <webElementGuid>6cc4002c-ec5c-4858-b3fd-a2270ceafed8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bedding Options'])[1]/following::span[1]</value>
      <webElementGuid>29b99fdc-7697-482e-a21e-6bde8470de1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bedding'])[1]/following::span[1]</value>
      <webElementGuid>3c6761c9-f7e3-456f-a9cf-c4ae2197b5e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dining'])[1]/preceding::span[2]</value>
      <webElementGuid>7dcf8431-e4a8-4d16-8c89-26f3c94b2603</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dining Options'])[1]/preceding::span[3]</value>
      <webElementGuid>d98bfebd-3cc2-4816-9e85-a5ef77a0b515</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Select bedding']/parent::*</value>
      <webElementGuid>3b9ac672-5afa-492e-b657-87c79b2cb78a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/span</value>
      <webElementGuid>42377095-5f40-472b-b1b3-fa6045bb19b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'bedding-input-option' and (text() = 'Select bedding' or . = 'Select bedding')]</value>
      <webElementGuid>15334215-258c-4c7a-9894-9cc8d6d56aa0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
