<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Location</name>
   <tag></tag>
   <elementGuidId>04d801e1-3600-4784-bc9a-65d67705b7f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#header11-cabinLocation</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='header11-cabinLocation']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7a500798-9701-40f5-aafe-5cad5232eb87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>header11-cabinLocation</value>
      <webElementGuid>3a28b9a7-ee1d-4d4b-bb31-41212a051830</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ms-DetailsHeader-cellTitle cellTitle-173</value>
      <webElementGuid>b21fdebd-01d9-45d7-a8b8-2f01ec1bf6bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Location</value>
      <webElementGuid>80e67c85-db23-4ffb-9527-e121163c320c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header11-cabinLocation&quot;)</value>
      <webElementGuid>4da97b6a-6800-4e8e-9db6-0da11efc63f6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='header11-cabinLocation']</value>
      <webElementGuid>078c0b6f-3327-4fea-a949-86e7b466d322</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gatsby-focus-wrapper']/div/main/div/div/form/fieldset/div[7]/div/div/div/div/div[4]/span/span</value>
      <webElementGuid>e7bb295e-a8d1-441b-af2c-323096c64491</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deck'])[1]/following::span[2]</value>
      <webElementGuid>f55e5dc4-8277-47f1-977e-1ee89a0221b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cabin'])[2]/following::span[5]</value>
      <webElementGuid>6f9e3aa5-8d54-400a-b412-9a4e0bca4e03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Obstruction'])[1]/preceding::span[2]</value>
      <webElementGuid>19d03feb-791d-4df2-902d-5843c40da755</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/span/span</value>
      <webElementGuid>456a637a-7666-439c-8e2b-a44874bb1eb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'header11-cabinLocation' and (text() = 'Location' or . = 'Location')]</value>
      <webElementGuid>10d1ad49-715f-4652-9242-5d9a7052cd3b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
