<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Accessibility</name>
   <tag></tag>
   <elementGuidId>124c6db3-2a6a-4868-964e-cdfea0893ea6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#header11-cabinAccessibility-name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='header11-cabinAccessibility-name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e661e1fb-e3d4-434f-8ee6-b1b5543b3da8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>header11-cabinAccessibility-name</value>
      <webElementGuid>245a44d3-72de-4e03-a224-5e432291d406</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ms-DetailsHeader-cellName cellName-174</value>
      <webElementGuid>eb6f14ec-0b5b-4479-afb0-476070efb9f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Accessibility</value>
      <webElementGuid>2927e56a-657b-47f3-a763-0275a64cdbc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header11-cabinAccessibility-name&quot;)</value>
      <webElementGuid>0e16b5b0-7a68-4e3d-a50d-1b695fb7ae48</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='header11-cabinAccessibility-name']</value>
      <webElementGuid>2332c211-763d-48df-9727-989243562396</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='header11-cabinAccessibility']/span</value>
      <webElementGuid>62601626-732d-4de9-a0e6-b38858992573</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Obstruction'])[1]/following::span[3]</value>
      <webElementGuid>3fbc73ad-f17c-4558-952a-d98b74082918</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Location'])[1]/following::span[6]</value>
      <webElementGuid>bfa14cbf-a5d8-4e6c-9208-3b2b33fc22ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='D726'])[1]/preceding::span[2]</value>
      <webElementGuid>8eb7b2dd-1063-4898-89ef-dc409bb85e67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dolphin'])[1]/preceding::span[3]</value>
      <webElementGuid>ad8dbb75-cbc1-4190-88f9-ef1e0fe3c16c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Accessibility']/parent::*</value>
      <webElementGuid>1a2873ea-ac02-4d82-8659-dc560c058d6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/span/span/span</value>
      <webElementGuid>7b086e22-41a5-4c4a-b641-b6a54d363a40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'header11-cabinAccessibility-name' and (text() = 'Accessibility' or . = 'Accessibility')]</value>
      <webElementGuid>8323aa3d-8cf7-4804-86ee-0d2c10d3c25b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
