<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Special Requests_special-request-input</name>
   <tag></tag>
   <elementGuidId>dd63e426-350a-4923-b75b-ac98986b9c44</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#special-request-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='special-request-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>8887b331-ea19-471c-89d1-fb563e81d7f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>special-request-input</value>
      <webElementGuid>57e9e67d-11fd-41d3-bea6-2c7947bb0312</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Type here...</value>
      <webElementGuid>cea72780-d5f4-4d95-868d-98ac0324882f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ms-TextField-field field-217</value>
      <webElementGuid>2332cde8-9771-450a-9b44-6683d5966a73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>TextFieldLabel16</value>
      <webElementGuid>81392af6-ac90-4c69-9688-80936862c630</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>488cbb12-756e-4dd6-a72f-ef61e2786810</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;special-request-input&quot;)</value>
      <webElementGuid>d7c3e98c-9b7e-44e1-a4cc-afa8b2bffda6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='special-request-input']</value>
      <webElementGuid>424442b2-d21e-4332-bb6e-12d320c6c86f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gatsby-focus-wrapper']/div/main/div/div/form/div[2]/div/div[7]/div/div/div/textarea</value>
      <webElementGuid>f85e06e0-de6f-4d12-b677-a2d3cbdf8668</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>35fdb214-3a0e-4cba-8f36-cc4c29591383</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'special-request-input' and @placeholder = 'Type here...']</value>
      <webElementGuid>3595806c-4125-472f-a24c-b0e1921bb2a8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
