<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>th_Cabin</name>
   <tag></tag>
   <elementGuidId>dab71835-8330-4f4c-ad92-98d494f8d464</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>th.CabinGuaranteedList-module--max-width--96RLn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='gatsby-focus-wrapper']/div/main/div/div/form/fieldset/div/table/thead/tr/th[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>th</value>
      <webElementGuid>75ac47ed-3a6f-4877-9fbc-0618281454a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>CabinGuaranteedList-module--max-width--96RLn</value>
      <webElementGuid>8ca4b34b-82d7-4237-866a-92a30af82171</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scope</name>
      <type>Main</type>
      <value>col</value>
      <webElementGuid>4b6572c7-4a5c-4f10-9dbc-1a4aa2bd3e39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cabin</value>
      <webElementGuid>b39c30dd-df95-424b-a176-7ebbf3b15047</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gatsby-focus-wrapper&quot;)/div[@class=&quot;GenericLayout-module--container--9rlo1&quot;]/main[1]/div[@class=&quot;ms-Stack css-98&quot;]/div[@class=&quot;ms-StackItem css-99&quot;]/form[1]/fieldset[@class=&quot;RadioGroup-module--fieldSet--z7Pz6 RadioGroup-module--is-not-padded--ZTKo5&quot;]/div[@class=&quot;GridRow-module--grid-row--inJvQ CabinGuaranteedList-module--container--RznIT&quot;]/table[1]/thead[1]/tr[1]/th[@class=&quot;CabinGuaranteedList-module--max-width--96RLn&quot;]</value>
      <webElementGuid>fb925b69-c4e3-41aa-b779-ca18a93f303b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gatsby-focus-wrapper']/div/main/div/div/form/fieldset/div/table/thead/tr/th[2]</value>
      <webElementGuid>8f74dbcd-7320-4234-b008-21daa4f57356</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Grade'])[1]/following::th[1]</value>
      <webElementGuid>e01e9510-13a7-4c90-b0fc-8106ac28788f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Guaranteed Cabin'])[1]/following::th[2]</value>
      <webElementGuid>ed25439b-b97b-4e99-957c-6787ad8bad9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Guaranteed Cabin'])[2]/preceding::th[2]</value>
      <webElementGuid>c889819b-67f3-4051-89b2-fe774ad70afb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Guaranteed Cabin'])[3]/preceding::th[2]</value>
      <webElementGuid>f3cb01f0-e956-4e40-b671-26306d283fbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cabin']/parent::*</value>
      <webElementGuid>ccf93a79-ca3b-4585-a7ac-626efb334244</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[2]</value>
      <webElementGuid>a56f9492-0475-4701-a4c8-d9387833de19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//th[(text() = 'Cabin' or . = 'Cabin')]</value>
      <webElementGuid>847b5f4c-0553-42ca-ba06-1687551f22c9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
