<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>th_Grade</name>
   <tag></tag>
   <elementGuidId>f719721b-4478-4334-a0ad-f4137eeece13</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>th</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='gatsby-focus-wrapper']/div/main/div/div/form/fieldset/div/table/thead/tr/th</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>th</value>
      <webElementGuid>33bea442-bf7f-4d59-a2f1-f1ca50de8fc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scope</name>
      <type>Main</type>
      <value>col</value>
      <webElementGuid>1e691173-329b-4b73-b286-ce27479ea504</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Grade</value>
      <webElementGuid>e7afeaed-4ef8-461a-aad4-437df3756df2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gatsby-focus-wrapper&quot;)/div[@class=&quot;GenericLayout-module--container--9rlo1&quot;]/main[1]/div[@class=&quot;ms-Stack css-98&quot;]/div[@class=&quot;ms-StackItem css-99&quot;]/form[1]/fieldset[@class=&quot;RadioGroup-module--fieldSet--z7Pz6 RadioGroup-module--is-not-padded--ZTKo5&quot;]/div[@class=&quot;GridRow-module--grid-row--inJvQ CabinGuaranteedList-module--container--RznIT&quot;]/table[1]/thead[1]/tr[1]/th[1]</value>
      <webElementGuid>1f509767-149a-456a-9bb5-7411776d5377</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gatsby-focus-wrapper']/div/main/div/div/form/fieldset/div/table/thead/tr/th</value>
      <webElementGuid>e85a2c8a-4d44-41a6-9352-ee0692733bc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Guaranteed Cabin'])[1]/following::th[1]</value>
      <webElementGuid>8be68125-cf20-4819-bd3e-6956a6eccc21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='cabin-select'])[1]/following::th[1]</value>
      <webElementGuid>f606d86d-d838-4d21-96a0-a1061a6b09d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cabin'])[1]/preceding::th[1]</value>
      <webElementGuid>ee4eca4e-d085-46e3-8a0c-32ce85780637</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Guaranteed Cabin'])[2]/preceding::th[3]</value>
      <webElementGuid>357627be-06d9-4225-8d02-0f8e7c246073</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Grade']/parent::*</value>
      <webElementGuid>2d8c113e-b676-4afc-b0d1-6728d27b24d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th</value>
      <webElementGuid>be9f1f19-1652-4b30-99eb-d319f17d0864</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//th[(text() = 'Grade' or . = 'Grade')]</value>
      <webElementGuid>64bd2e5f-7e86-46b2-8d74-3467307726a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
