<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_searchsearchresultsresults</name>
   <tag></tag>
   <elementGuidId>99cc8051-3376-4120-99eb-feef822872ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='gatsby-focus-wrapper']/div/main/div/div[2]/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.GridColumn-module--grid-column--fqCL9.GridColumn-module--size-9--3CuBP.GridColumn-module--grid-column--padded--TTiI2 > div.ms-Stack.css-160 > div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e3e74253-e0ac-41eb-a79b-a8c754c6d2d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>searchsearchresultsresults</value>
      <webElementGuid>1ed0fea6-2b9c-4b72-a574-d856ca771e41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gatsby-focus-wrapper&quot;)/div[@class=&quot;GenericLayout-module--container--9rlo1&quot;]/main[1]/div[@class=&quot;GridRow-module--grid-row--inJvQ GridRow-module--grid-row--padded--fWrJ3&quot;]/div[@class=&quot;GridColumn-module--grid-column--fqCL9 GridColumn-module--size-9--3CuBP GridColumn-module--grid-column--padded--TTiI2&quot;]/div[@class=&quot;ms-Stack css-160&quot;]/div[1]</value>
      <webElementGuid>8a0647bd-2f0a-4c76-9493-723282b0762e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gatsby-focus-wrapper']/div/main/div/div[2]/div/div</value>
      <webElementGuid>83904817-e0e6-410a-bf59-552bf413e2d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Price range'])[1]/following::div[10]</value>
      <webElementGuid>c1d17e63-41c7-4a9a-b1ab-c6c86a3b6a14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zuiderdam (13)'])[1]/following::div[12]</value>
      <webElementGuid>6efbb1f1-ec21-49f9-b656-3e9f59aaa276</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div</value>
      <webElementGuid>50c7b422-686b-41f7-b1ff-ed609da458f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'searchsearchresultsresults' or . = 'searchsearchresultsresults')]</value>
      <webElementGuid>8d11c7f5-6e0a-42d1-8f67-8bcfb24e4e86</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
