<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Passenger Ages</name>
   <tag></tag>
   <elementGuidId>b8d8b83c-f220-4cdb-8502-19d8f4137e11</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ModalFocusTrapZone817']/div[2]/form/div/div[2]/div[2]/div/h2</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>06198072-ebdd-46f0-85e1-be94490158bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>results-module--modal-headings--+5iOZ</value>
      <webElementGuid>03e7ecb6-8b3c-4339-a90f-3a58a5cf3746</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Passenger Ages</value>
      <webElementGuid>07cd8862-4494-4e86-b134-6ebab023281b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ModalFocusTrapZone817&quot;)/div[@class=&quot;ms-Modal-scrollableContent scrollableContent-204&quot;]/form[1]/div[@class=&quot;ms-Stack css-239&quot;]/div[@class=&quot;ms-Stack css-241&quot;]/div[@class=&quot;ms-Stack css-160&quot;]/div[@class=&quot;ms-Stack css-185&quot;]/h2[@class=&quot;results-module--modal-headings--+5iOZ&quot;]</value>
      <webElementGuid>f8733c01-1356-4bc4-8150-ed4c0636aaf3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ModalFocusTrapZone817']/div[2]/form/div/div[2]/div[2]/div/h2</value>
      <webElementGuid>e559cfc2-a0b8-4254-9b4f-ed58f700f35f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No. of Passengers'])[1]/following::h2[1]</value>
      <webElementGuid>b9633ae5-8925-4933-b5b2-34ea525a2d70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please fill out the following information for more accurate pricing'])[1]/following::h2[1]</value>
      <webElementGuid>171de5fb-6fbd-4e8c-8d59-c84f77403766</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Input age of passenger on return date.'])[1]/preceding::h2[1]</value>
      <webElementGuid>49ba415f-b59d-4022-9cd1-991009ce2818</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Passenger 1'])[1]/preceding::h2[1]</value>
      <webElementGuid>bc032ee3-1599-4847-9665-d9279cbe3097</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Passenger Ages']/parent::*</value>
      <webElementGuid>0eb6b137-9da4-4ea1-a040-4af5fbdd40af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/h2</value>
      <webElementGuid>a267dfe8-6f9f-456e-9cc1-ce6dd75f3d33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'Passenger Ages' or . = 'Passenger Ages')]</value>
      <webElementGuid>1f652489-a10f-4e55-bb45-d77fd5cafb00</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
