<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_(found 979, showing 979)_ms-Image-image_2b24c6</name>
   <tag></tag>
   <elementGuidId>7c8f27a7-f1f4-445b-b87a-2491ab635d47</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='gatsby-focus-wrapper']/div/main/div/div[2]/div/ul/li/div/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.ms-Image-image.is-loaded.ms-Image-image--cover.ms-Image-image--landscape.is-fadeIn.image-222</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>885df2cc-5687-4424-a0f6-cac0ce309359</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Image of Queen Anne</value>
      <webElementGuid>e4eaa647-a546-41d9-a8f0-1be5f8a9cb81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://static.traveltek.net/cruisepics/local_shipimages_small/1644402555.png</value>
      <webElementGuid>ec5b6da1-d9da-453a-9b67-7d20e02abe71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ms-Image-image is-loaded ms-Image-image--cover ms-Image-image--landscape is-fadeIn image-222</value>
      <webElementGuid>5d86611a-6c11-491d-883f-2cffabd6bdb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gatsby-focus-wrapper&quot;)/div[@class=&quot;GenericLayout-module--container--9rlo1&quot;]/main[1]/div[@class=&quot;GridRow-module--grid-row--inJvQ GridRow-module--grid-row--padded--fWrJ3&quot;]/div[@class=&quot;GridColumn-module--grid-column--fqCL9 GridColumn-module--size-9--3CuBP GridColumn-module--grid-column--padded--TTiI2&quot;]/div[@class=&quot;ms-Stack css-160&quot;]/ul[@class=&quot;ResultsList-module--list--+ZCDo List-module--list-unstyled--OYpBm&quot;]/li[@class=&quot;ResultsListItem-module--container--3g6pa&quot;]/div[@class=&quot;ms-Stack css-185&quot;]/div[@class=&quot;ms-StackItem css-186&quot;]/div[@class=&quot;ms-Image root-221&quot;]/img[@class=&quot;ms-Image-image is-loaded ms-Image-image--cover ms-Image-image--landscape is-fadeIn image-222&quot;]</value>
      <webElementGuid>f230c823-15fe-4959-a0bc-34febbdd1778</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gatsby-focus-wrapper']/div/main/div/div[2]/div/ul/li/div/div/div/img</value>
      <webElementGuid>154383bc-0e4c-4db1-b0c1-4447d7e8d252</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Image of Queen Anne']</value>
      <webElementGuid>1c45b06d-9fbd-4b74-b140-1a5dbef50a87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>67442eba-2e12-4b73-9a14-c112ce255441</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Image of Queen Anne' and @src = 'https://static.traveltek.net/cruisepics/local_shipimages_small/1644402555.png']</value>
      <webElementGuid>a147f2dc-cf7f-434d-a473-9a78d45941b8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
