<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Traveltek Cruise Search</name>
   <tag></tag>
   <elementGuidId>e58ab9ba-b1b6-454f-8c59-480fb0861b24</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h1.Heading-module--title--V5kOu.Heading-module--title-1--XBLzA.Heading-module--weight-normal--lFvwH</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='gatsby-focus-wrapper']/div/div/h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>49fe06ba-7749-4f32-bd8e-17178adafbb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Heading-module--title--V5kOu Heading-module--title-1--XBLzA Heading-module--weight-normal--lFvwH</value>
      <webElementGuid>9f658d2d-a2c0-4ebc-8a6a-f671d6d412c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Traveltek Cruise Search</value>
      <webElementGuid>1592da29-abb4-4cbf-a49a-67d5c29b3d4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gatsby-focus-wrapper&quot;)/div[@class=&quot;GenericLayout-module--container--9rlo1&quot;]/div[@class=&quot;GenericLayout-module--header--jiLjT&quot;]/h1[@class=&quot;Heading-module--title--V5kOu Heading-module--title-1--XBLzA Heading-module--weight-normal--lFvwH&quot;]</value>
      <webElementGuid>0c390400-1b5f-44a2-8f36-c64e36e76093</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gatsby-focus-wrapper']/div/div/h1</value>
      <webElementGuid>6558512e-cbfe-42bc-8305-b39295e9758c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filter'])[1]/preceding::h1[1]</value>
      <webElementGuid>564ce154-9060-44ed-bb13-a484884a3341</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cruise Line'])[1]/preceding::h1[1]</value>
      <webElementGuid>e047de1a-31ad-47f4-a7eb-907f96a8485f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Traveltek Cruise Search']/parent::*</value>
      <webElementGuid>f58918e7-2a94-4ce0-9adf-cfbde54330d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>8fac3984-f58a-42fa-8117-7904544ea6b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'Traveltek Cruise Search' or . = 'Traveltek Cruise Search')]</value>
      <webElementGuid>672d552b-93ce-4d00-af68-99f9ee5c7706</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
