<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Cabins</name>
   <tag></tag>
   <elementGuidId>907a393a-88c9-4f32-ae2e-7dff771275c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ModalFocusTrapZone835']/div[2]/form/div/div[4]/h2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>985fab76-3e74-4c1d-88f8-66486fb477e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>results-module--modal-headings--+5iOZ</value>
      <webElementGuid>01770949-906d-4fc4-95be-aa29174cc95d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cabins</value>
      <webElementGuid>5f8ce304-6ac9-44ee-914c-f17b2bbbcda0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ModalFocusTrapZone835&quot;)/div[@class=&quot;ms-Modal-scrollableContent scrollableContent-204&quot;]/form[1]/div[@class=&quot;ms-Stack css-239&quot;]/div[@class=&quot;ms-Stack css-162&quot;]/h2[@class=&quot;results-module--modal-headings--+5iOZ&quot;]</value>
      <webElementGuid>eacde69a-c6c0-4204-9ea1-e16a354dcb8a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ModalFocusTrapZone835']/div[2]/form/div/div[4]/h2</value>
      <webElementGuid>b2d5d871-0353-439d-aa1d-b25df61ca926</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Residential Rates'])[1]/following::h2[1]</value>
      <webElementGuid>d6f3e456-68f2-402f-afdd-1150b3ef8f76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Military Rates'])[1]/following::h2[1]</value>
      <webElementGuid>04f4b0f8-5d2e-4bd9-bb7a-a46f357ad62f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Accessible Cabins'])[1]/preceding::h2[1]</value>
      <webElementGuid>01245a0a-1e64-46d7-acf3-37907d002525</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::h2[1]</value>
      <webElementGuid>2ad1fa4f-2d72-4c5d-96f5-47dcf654babe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cabins']/parent::*</value>
      <webElementGuid>14435671-f32b-40f8-9b63-455c010e2bba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/h2</value>
      <webElementGuid>f070c723-eecd-4bc7-897d-95f1271016c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'Cabins' or . = 'Cabins')]</value>
      <webElementGuid>4f5ae218-1e4c-48fe-905d-c1f03f9aa078</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
