<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Rates</name>
   <tag></tag>
   <elementGuidId>5502b985-59e0-4701-800f-8f9a7bb04ab0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Passenger 2'])[1]/following::h2[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>6dd48418-c489-4912-ac6c-3e6ad548e358</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>results-module--modal-headings--+5iOZ</value>
      <webElementGuid>7976ff9b-4c9a-4ce6-aecf-c3b40218558d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Rates</value>
      <webElementGuid>4e959ad5-9f43-4bc3-b547-fa92fb7a2239</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ModalFocusTrapZone835&quot;)/div[@class=&quot;ms-Modal-scrollableContent scrollableContent-204&quot;]/form[1]/div[@class=&quot;ms-Stack css-239&quot;]/div[@class=&quot;ms-Stack css-162&quot;]/h2[@class=&quot;results-module--modal-headings--+5iOZ&quot;]</value>
      <webElementGuid>81c8a698-8f71-4cc7-a72c-8cb8a1377eff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ModalFocusTrapZone835']/div[2]/form/div/div[3]/h2</value>
      <webElementGuid>2fe3d3d7-b11a-47da-ab10-bb4c5b229be5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Passenger 2'])[1]/following::h2[1]</value>
      <webElementGuid>64866831-88f0-499c-b84a-6d3463e40811</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Passenger 1'])[1]/following::h2[1]</value>
      <webElementGuid>b4d240ca-b1b9-4929-abca-d13d2bf46bca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Military Rates'])[1]/preceding::h2[1]</value>
      <webElementGuid>6338d7e8-c279-436a-8312-bb4132f71a90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Residential Rates'])[1]/preceding::h2[1]</value>
      <webElementGuid>2434f4f7-73f6-4dda-91ae-fe392c2ed517</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Rates']/parent::*</value>
      <webElementGuid>c1fbcb43-5245-4772-832a-7eb378a567e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/h2</value>
      <webElementGuid>9fe5a424-cf04-4b1e-83cf-e1b6c433a95c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'Rates' or . = 'Rates')]</value>
      <webElementGuid>e07f5c10-b8ad-450a-81b5-4a970bcbf12f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
