<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Destination_destination-auto-suggest-input</name>
   <tag></tag>
   <elementGuidId>44dfc75d-4ca3-4c3c-81ea-e77afcbcb216</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#destination-auto-suggest-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='destination-auto-suggest-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a915b46d-4b52-4393-bec2-bd890e3d1a49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ee5c41e8-df71-4638-a765-9111e4b633e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>destination-auto-suggest-input</value>
      <webElementGuid>217eaa74-aad6-400a-b600-0ff0d37b9597</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Any...</value>
      <webElementGuid>3c8d9607-a12e-4ddd-b6b8-e98f57c5ad71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>06e0b998-8943-4e2f-8708-f38071670b45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>76e9544a-322c-4161-9f1d-7f5dfe704f9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>react-autowhatever-1</value>
      <webElementGuid>ca691b00-8245-45f1-af18-35ee30fc61cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ms-TextField-field field-158</value>
      <webElementGuid>c303c013-85cc-4ed0-8650-4499b65bad72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>TextFieldLabel2</value>
      <webElementGuid>9d60e2c2-75c2-487b-8c3b-4ba1e27cda90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7ec6474e-4c07-4756-adb1-d5d9ad1b29f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;destination-auto-suggest-input&quot;)</value>
      <webElementGuid>918df68e-efa8-4672-bf23-34d23db10103</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='destination-auto-suggest-input']</value>
      <webElementGuid>a062bbe5-164a-49c8-9645-39d117617da3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gatsby-focus-wrapper']/div/main/form/div/div/div/div/div/div/div/input</value>
      <webElementGuid>a4e50b7c-833e-4cbf-a1a5-ea4685e23be5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>756027f8-62cd-44a7-9a46-1ab05e9d240b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'destination-auto-suggest-input' and @placeholder = 'Any...']</value>
      <webElementGuid>432ed828-218b-4629-9f21-4c81657cdd60</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
