<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_No. of Passengers</name>
   <tag></tag>
   <elementGuidId>e29d3991-a618-4d0d-876a-da109ee3fbab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Dropdown3003-label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='Dropdown3003-label']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>f3e3c95a-b805-409d-ace3-086ca8d17b11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ms-Label ms-Dropdown-label label-244</value>
      <webElementGuid>18e4420c-bcdc-4317-a442-837ffa97adf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Dropdown3003-label</value>
      <webElementGuid>5f0e5f1c-4d71-4e66-9556-9c4baa0ed5ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>No. of Passengers</value>
      <webElementGuid>f0a66cad-66c6-4630-a94f-96b9b608d417</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Dropdown3003-label&quot;)</value>
      <webElementGuid>eae22989-b07d-481e-ad0d-41d39addc680</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='Dropdown3003-label']</value>
      <webElementGuid>f835a671-0478-4956-9227-98f0bfddcbce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ModalFocusTrapZone835']/div[2]/form/div/div[2]/div/label</value>
      <webElementGuid>c8f17c23-6fdf-4d9d-b99d-9ea999da5730</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please fill out the following information for more accurate pricing'])[1]/following::label[1]</value>
      <webElementGuid>5eb9b15a-564a-4c8c-813e-c75edbfbb5c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Passenger Information'])[1]/following::label[1]</value>
      <webElementGuid>3017475f-ab8e-4f24-9aae-f14bd6a501aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Passenger Ages'])[1]/preceding::label[1]</value>
      <webElementGuid>5ea2c6bd-5603-4c63-8cf3-d850a62fdd86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Input age of passenger on return date.'])[1]/preceding::label[1]</value>
      <webElementGuid>a65dcd65-fde3-4c6c-9f88-81004ec2ea14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='No. of Passengers']/parent::*</value>
      <webElementGuid>7b25677d-5472-42ac-b7a9-4cef1bd629c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/label</value>
      <webElementGuid>17091fdd-5488-4deb-870a-09e677ee42dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'Dropdown3003-label' and (text() = 'No. of Passengers' or . = 'No. of Passengers')]</value>
      <webElementGuid>5bfca117-a273-405f-b91f-b8b0fdd6c9cf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
