<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Departure Start Date</name>
   <tag></tag>
   <elementGuidId>7ac20589-1f5c-4028-a380-3eee8ca5efaa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#TextFieldLabel9</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='TextFieldLabel9']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>7132ccb3-0364-4206-a76f-985f2d97b2e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>DatePicker5-label</value>
      <webElementGuid>f9adfea3-23ce-432e-a30a-09318cdc76a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TextFieldLabel9</value>
      <webElementGuid>c556238a-3e65-42f2-ad0a-2b778662b07f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ms-Label root-114</value>
      <webElementGuid>e2d6d12c-f750-40ac-9cd2-0ecfa54c24f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Departure Start Date</value>
      <webElementGuid>d6f4d2c6-d22d-4b79-87cb-c1d50b888aaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TextFieldLabel9&quot;)</value>
      <webElementGuid>cf14588f-c207-43ad-a095-08dada5d222d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='TextFieldLabel9']</value>
      <webElementGuid>9b50a819-3c29-4ab8-997a-ce57d447108e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gatsby-focus-wrapper']/div/main/form/div/div/div[2]/div/div/div/div/label</value>
      <webElementGuid>6c24768f-418b-4718-aa83-cdc3ab7f8d3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Destination'])[1]/following::label[1]</value>
      <webElementGuid>46552596-13c4-4a79-96a5-72d609723773</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Traveltek Cruise Search'])[1]/following::label[2]</value>
      <webElementGuid>890ed9b8-81b9-4f72-81cc-c38f9777fb6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tue Aug 30 2022'])[1]/preceding::label[1]</value>
      <webElementGuid>2cf221d8-ac7a-413b-a681-2a3fadbde382</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Departure End Date'])[1]/preceding::label[1]</value>
      <webElementGuid>971493e0-96d8-40d2-8e52-4513889c1aec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Departure Start Date']/parent::*</value>
      <webElementGuid>85f06a3a-01c7-43c9-9519-b42c28723a52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/label</value>
      <webElementGuid>bca22833-9110-41f5-ae3d-e0c77cdb0680</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'TextFieldLabel9' and (text() = 'Departure Start Date' or . = 'Departure Start Date')]</value>
      <webElementGuid>2a4b57b0-d0a5-46d7-976c-6bc07258d76c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
