<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Passenger 2</name>
   <tag></tag>
   <elementGuidId>a911e797-3d35-41ba-b89f-3e2684396f76</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#TextFieldLabel3015</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Rates'])[1]/preceding::label[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>bef140a5-86b1-42cb-b302-ac5a584fcab9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>TextField3013</value>
      <webElementGuid>dd259d69-5318-4ad2-a0fc-f15e1fec33f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TextFieldLabel3015</value>
      <webElementGuid>0034fb5f-590c-4e8c-96cf-020dfb361ffb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ms-Label root-247</value>
      <webElementGuid>45e1ca78-3bea-441e-ae25-ae295d1ebbc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Passenger 2</value>
      <webElementGuid>3a12bee3-a9be-4815-8b5d-a1af0d48dbc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TextFieldLabel3015&quot;)</value>
      <webElementGuid>82be4712-6bb0-4a49-bd91-c633f3a18734</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='TextFieldLabel3015']</value>
      <webElementGuid>064208b4-0fd9-4e25-a457-cc9a6f448dde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ModalFocusTrapZone835']/div[2]/form/div/div[2]/div[2]/div[3]/div/label</value>
      <webElementGuid>519555cc-ea4d-4b34-a2d6-1d166a45fb87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Passenger 1'])[1]/following::label[1]</value>
      <webElementGuid>75bffa24-e0f6-4e61-bd66-bb039966bebd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Input age of passenger on return date.'])[1]/following::label[2]</value>
      <webElementGuid>f3d5d787-dbc6-411f-aad1-df97fcfcef24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rates'])[1]/preceding::label[1]</value>
      <webElementGuid>b431f66f-256b-4a8f-a796-4b29dc60f63e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Military Rates'])[1]/preceding::label[1]</value>
      <webElementGuid>697ab438-b5b1-453a-b105-9473e1f068c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Passenger 2']/parent::*</value>
      <webElementGuid>b1ae3f89-c8b8-4c04-b888-aea2e36ffc47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div/label</value>
      <webElementGuid>af75d10a-7d11-4a2c-8876-5a9a291beb90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'TextFieldLabel3015' and (text() = 'Passenger 2' or . = 'Passenger 2')]</value>
      <webElementGuid>035e3778-ae95-4757-94fb-1df9dc14d6b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
