<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Passenger 2</name>
   <tag></tag>
   <elementGuidId>a911e797-3d35-41ba-b89f-3e2684396f76</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#TextFieldLabel3015</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='TextFieldLabel3015']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>e566198a-6e07-4e8d-900d-e840693791b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>TextField3013</value>
      <webElementGuid>72dc416f-3361-46ba-bb2c-dda070947140</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TextFieldLabel3015</value>
      <webElementGuid>976ac122-067f-4cc0-a16b-bc99ea76a1cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ms-Label root-247</value>
      <webElementGuid>0414efbe-348b-4eb6-98c5-a72b615be1ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Passenger 2</value>
      <webElementGuid>791b226f-3b6d-4d2a-85e5-40fefa7be83b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TextFieldLabel3015&quot;)</value>
      <webElementGuid>b6598e28-7ee4-47a9-8816-19c28844b221</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='TextFieldLabel3015']</value>
      <webElementGuid>505cba9d-e41c-4983-bb98-1a3fb38e2d1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ModalFocusTrapZone835']/div[2]/form/div/div[2]/div[2]/div[3]/div/label</value>
      <webElementGuid>05d04431-5d4b-426a-8a03-84c558762730</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Passenger 1'])[1]/following::label[1]</value>
      <webElementGuid>cdf291cc-4d77-4e63-8021-40125a7c9272</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Input age of passenger on return date.'])[1]/following::label[2]</value>
      <webElementGuid>c62c3364-eec4-43a6-8123-b07fb14d29d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rates'])[1]/preceding::label[1]</value>
      <webElementGuid>982c72e2-d2de-4f47-a398-05b6971dcbd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Military Rates'])[1]/preceding::label[1]</value>
      <webElementGuid>7897cfd8-9471-4c37-9416-ebc2573740e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Passenger 2']/parent::*</value>
      <webElementGuid>bb7ed415-7bdb-4202-927b-341e0d125ee0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div/label</value>
      <webElementGuid>34f1bd0b-336b-43a1-937b-0db149bfb387</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'TextFieldLabel3015' and (text() = 'Passenger 2' or . = 'Passenger 2')]</value>
      <webElementGuid>bf42b9f2-13a6-4f4f-889b-0feb01ce11bf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
