<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Passenger 1</name>
   <tag></tag>
   <elementGuidId>6c89df79-ee5e-421b-9cac-07f31002a90a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#TextFieldLabel3010</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='TextFieldLabel3010']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>cf1ad173-c0df-4166-93f6-22b35be78ed5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>TextField3008</value>
      <webElementGuid>87926ed2-c3b6-4125-bc51-a4ab07d36604</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TextFieldLabel3010</value>
      <webElementGuid>b4793e94-cd58-44ac-8bdf-60ed815c2373</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ms-Label root-247</value>
      <webElementGuid>22ac0d87-b897-46f2-8b5b-e6a542b253fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Passenger 1</value>
      <webElementGuid>3083a323-5c37-4d81-ba6e-861fb0f26c3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TextFieldLabel3010&quot;)</value>
      <webElementGuid>5b3ad1ec-efaa-4d1a-b682-a38a086765c6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='TextFieldLabel3010']</value>
      <webElementGuid>0dcc3a17-ad05-43b3-963c-3c2e14d4cbe8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ModalFocusTrapZone835']/div[2]/form/div/div[2]/div[2]/div[2]/div/label</value>
      <webElementGuid>d4698bbd-18ca-4a05-94d7-1127dae66b80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Input age of passenger on return date.'])[1]/following::label[1]</value>
      <webElementGuid>bdd03217-5d80-46ba-82d6-e4109e5a73a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Passenger Ages'])[1]/following::label[1]</value>
      <webElementGuid>b9bfaa9c-c8b6-4bfc-90ea-75b6b906f1e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Passenger 2'])[1]/preceding::label[1]</value>
      <webElementGuid>ebe5b612-4ffd-488f-83cc-2d849e4174e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rates'])[1]/preceding::label[2]</value>
      <webElementGuid>5ce0f562-7971-429f-808b-a69adf94e355</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Passenger 1']/parent::*</value>
      <webElementGuid>5276a941-fe75-4abb-84d3-4010b63c5e0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/label</value>
      <webElementGuid>7b3fa96b-3083-4e19-a17c-630823db1b29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'TextFieldLabel3010' and (text() = 'Passenger 1' or . = 'Passenger 1')]</value>
      <webElementGuid>9cd42562-67e3-4193-9b50-9ae0241f82de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
