<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Confirm</name>
   <tag></tag>
   <elementGuidId>44f062bf-2145-47b4-a16a-6177cdd0705b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.ms-Stack.css-248 > button.ms-Button.ms-Button--primary.root-148 > span.ms-Button-flexContainer.flexContainer-149 > span.ms-Button-textContainer.textContainer-150</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ModalFocusTrapZone835']/div[2]/form/div/div[5]/button[2]/span/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0864af38-06bf-4a49-85bc-03f1536c31cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ms-Button-textContainer textContainer-150</value>
      <webElementGuid>77181ad0-a369-4b6b-9811-598d46eb7c93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Confirm</value>
      <webElementGuid>29ef3119-57cf-45f1-92f6-942c9c14c24e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ModalFocusTrapZone835&quot;)/div[@class=&quot;ms-Modal-scrollableContent scrollableContent-204&quot;]/form[1]/div[@class=&quot;ms-Stack css-239&quot;]/div[@class=&quot;ms-Stack css-248&quot;]/button[@class=&quot;ms-Button ms-Button--primary root-148&quot;]/span[@class=&quot;ms-Button-flexContainer flexContainer-149&quot;]/span[@class=&quot;ms-Button-textContainer textContainer-150&quot;]</value>
      <webElementGuid>23f56e95-df2a-468d-8352-307b3861cb36</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ModalFocusTrapZone835']/div[2]/form/div/div[5]/button[2]/span/span</value>
      <webElementGuid>5fbb088a-3ef1-4d09-b881-ee5308dc873d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/following::span[2]</value>
      <webElementGuid>9075abe9-1a4d-47c7-801e-4a190ddc976e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Accessible Cabins'])[1]/following::span[5]</value>
      <webElementGuid>706d2b9e-bd7c-41c1-b761-365f1b229835</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]/span/span</value>
      <webElementGuid>88f48d4b-f837-4683-922b-2ec150e896bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Confirm' or . = 'Confirm')]</value>
      <webElementGuid>92866f26-99dd-49e0-9d8f-eabfd8fc1a80</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
